Task1
FadeiKholyavo/sheduler-start pull request #1
Opened 2021-05-15 21:20 UTC by FadeiKholyavo

2021-05-15 21:30 UTC, FadeiKholyavo commented
[DB.zip](https://github.com/FadeiKholyavo/sheduler-start/files/6488255/DB.zip)

база данных

2021-05-17 07:58 UTC, VeraOrekh requested changes

2021-05-17 07:58 UTC, VeraOrekh commented on README.md
> +- clone or download the demo
Поменяй описание запуска приложения

2021-05-17 07:58 UTC, VeraOrekh commented on README.md
> +- import database from `mysql_dump.sql`
Добавь отдельный sql скрипт в репозиторий, где будут добавляться таблицы и все тестовые данные.
И ещё было бы неплохо, если бы все файлы, которые относятся к серверной части, лежали в отдельной папке

2021-05-17 07:58 UTC, VeraOrekh commented on public/js/scheduler-init.js
> +	const parseStartDate = scheduler.date.date_to_str("%l, %d. %F");
У тебя табуляция где-то через пробелы, где-то через табы. Должно быть что-то одно.
Такая проблема не только в этом месте

2021-05-17 07:58 UTC, VeraOrekh commented on public/js/scheduler-init.js
> +
Зачем аттачить два одинаковых ивента один за другим?

2021-05-17 07:58 UTC, VeraOrekh commented on public/js/scheduler-init.js
> +scheduler.config.xml_date="%Y-%m-%d %H:%i";
Конфиги, темлейты и ивент хендлеры разбросаны по всему файлу. Было бы лучше, если бы они были сгруппированы в файле

2021-05-17 07:58 UTC, VeraOrekh commented on server.js
> +    "host": "localhost",
Для значений для подключения к бд(host, user, password, database) лучше создать глобальные переменные, которые будут лежать в отдельном файле. Так, если нужно будет их поменять, не придётся искать каждый раз в коде эти значения и подменять их

2021-05-17 07:58 UTC, VeraOrekh commented on storage.js
> +		let result = await this._db.query(
Перед изменением данных в бд следует проверить, все ли данные верны

2021-05-17 16:02 UTC, ts-marina commented on public/css/event-box-style.css
> +    background-color: #009966 !important;
такой же стиль на строчке 11. можно объединить
так же со строчками 6 и 14; 19 и 22.

объединить как на строчке 25

2021-05-17 16:02 UTC, ts-marina commented on public/js/scheduler-init.js
> +scheduler.attachEvent("onTemplatesReady", () => {
вроде этот темплейт `scheduler.templates.event_header` необязательно оборачивать в `onTemplatesReady`
и тот, который на строчке 47 тоже

но если идет оборот в `onTemplatesReady`, то можно аттачить один раз `onTemplatesReady` и в нем описывать два темлейта:
```
 scheduler.attachEvent("onTemplatesReady", () => {
    scheduler.templates.event_header = (start, end, event) => {}
    scheduler.templates.event_text = (start, end, event) => {}
}); 
```

2021-05-17 16:02 UTC, ts-marina commented on public/js/scheduler-init.js
> +    return parseStartDate(start) +" &ndash; " + parseEndDate(endDate);
нужно придерживаться одного стиля построения строки.. везде используется шаблон `${}`, а тут конкатенация

2021-05-17 16:02 UTC, ts-marina commented on public/js/scheduler-init.js
> +	ev.text = ev.text.replace(/[<>]/g, "");
очень нехорошо получится, если юзеру действительно нужны будут эти символы в тексте.. 
поэтому такой вариант для юзера не подойдет
есть вариант перед сохранением переводить такие символы в html код (хэш) и хранить его так
а перед редактированием возвращать эти символы обратно

2021-05-20 05:48 UTC, ts-marina commented on README.md
> +- update db connection settings in `server.js`
локация файла изменилась. да и файл с конфигами используется другой

2021-05-20 05:54 UTC, ts-marina commented on README.md
> +## Run
как я поняла, это запускает только сервер. нет информации как запускать фронт (правильный путь, потому что вариантов запуска может быть много)

2021-05-20 06:02 UTC, ts-marina commented on public/js/scheduler-init.js
> +	return `${parseStartDate(start)} &ndash; ${parseEndDate(endDate)}`;
![image](https://user-images.githubusercontent.com/48479780/118927131-022aa600-b94a-11eb-8c59-974316f1444a.png)
не совпадает темплейт на week view
должно быть `"Monday, 22. February – Sunday, 28. February 2016 (week 8)"`

2021-05-20 06:13 UTC, ts-marina commented on public/js/scheduler-init.js
> +scheduler.createTimelineView({
![image](https://user-images.githubusercontent.com/48479780/118927901-220e9980-b94b-11eb-97f3-914ba47af380.png)
на timeline view timerange меньше чем на остальных вьюхах. из-за чего на нем показываются не все ивенты

2021-05-20 06:23 UTC, ts-marina commented on public/js/scheduler-init.js
> +// Config date in headers of day and month views
касательно стилей на month view 
можно используя этот темплейт `scheduler.templates.month_date_class` можно разукрасить background для cells, но только для тех, которые меньше сегодняшней даты
(ты спрашивал как закрасить под ивентами, под ивентами нельзя, но вот всю cell можно)

2021-05-20 06:25 UTC, ts-marina commented on public/css/event-box-color.css
> +/*event with fixed time, in month view*/
![image](https://user-images.githubusercontent.com/48479780/118929503-48353900-b94d-11eb-836b-10354a8509cf.png)
на month view ивенты не разукрашены в разные цвета

2021-05-20 06:37 UTC, VeraOrekh requested changes

2021-05-20 06:37 UTC, VeraOrekh commented on sheduler.sql
> +    PRIMARY KEY (`id`)
Нет foreign key для room & owner ids

2021-05-20 06:37 UTC, VeraOrekh commented on sheduler.sql
> +    `key` int DEFAULT null,
У таблиц rooms и owners нет primary key или уникального not null индекса

2021-05-21 05:55 UTC, ts-marina commented on public/js/scheduler-init.js
> +	if(date < new Date()) return "block_event";
лучше использовать timestamp для сравнения: `date.getTime() < new Date().getTime()` или `+date < +new Date()`

2021-05-21 06:02 UTC, ts-marina commented on public/js/scheduler-init.js
> +	if(date < new Date()) return "block_event";
немного нелогичное имя класса для ячейки дня на month view
block_event говорит что блокируется ивент, а не month_cell

2021-05-21 06:07 UTC, ts-marina commented on README.md
> +-  include `./js/scheduler-init.js` script to the `public/index.html`
файл  `./js/scheduler-init.js` уже подключен на странице.. а как стартануть страницу - все таки нет инструкции. 
запустить из папки?..
запустить через поднятый сервер?..
открыть определенную линку в брауре?..
и другие...

2021-05-21 09:02 UTC, VeraOrekh requested changes

2021-05-21 09:02 UTC, VeraOrekh commented on package.json
> +    "start": "node server.js",
Файл server.js лежит в другой папке, поменяй путь

2021-05-21 09:02 UTC, VeraOrekh commented on public/js/scheduler-init.js
> +	if(!event.owner_id) return `owner_0`
Забыл про точку с запятой в конце.
Обычно там, где нет никаких переменных, используются либо одинарные, либо двойные кавычки в зависимости от eslint

2021-05-21 09:02 UTC, VeraOrekh commented on sheduler.sql
> +CREATE TABLE `events` (
Т.к. ты создавал базу данных только в том случае, если её не существовало, то и логичнее при создании таблиц тоже указать ```CREATE TABLE IF NOT EXISTS```.
А если в последствии нужно вмести изменения в уже существующие таблицы, обычно старые не удаляют, заменяя их новыми. А просто ниже добавляют скрипт, которые вносят изменения

2021-05-21 10:22 UTC, VeraOrekh approved these changes

2021-05-21 11:19 UTC, ts-marina approved these changes

2021-05-21 11:21 UTC, merged